---
title: "Work Experience"
---

# Research

## **Hofmann Lab**
#### Austin, TX - The University of Texas at Austin
#### Fall 2025 - Present

My work in the Hofmann Lab involves spending 6-12 hours a week programming on the RStudio server, with tasks ranging from visualization of data to investigating papers for methods, functions, and packages to repurpose for our own project. Once a week, my lab partner and I meet with Dr. Hans Hofmann, our PI, to discuss progress of the week, analyze results, and decied on next steps. Additionally, I am preparing to present and compete at UT Austin's upcoming Undergraduate Research Forum with a clear 8-minute long presentation, a large-scale posterbord detailing our methods and findings. This project is still ongoing.

For more details on the project itself, please see the [projects tab](Projects.html).

------------------------------------------------------------------------

# Employment

## **Freshman Research Initiative Mentor**
#### Austin, TX - The University of Texas at Austin
#### January 2026 - May 2026

After completing my first year in the Freshman Research Initiative at UT Austin, I was selected to return as a mentor. I've been assigned a small group of undergraduates to meet with outside of class bi-weekly in order to guide them through problem sets, lectures, and a mini research project, using COVID-19 data.

Some of the skills I teach include understanding data biologically, learning Python and Linux commands, and comprehending scientific papers. The second half of the semester involves the students applying these skills to their own project, where they investigate differential gene expression in COVID-19 patients.

## **Statistics Course Grader**
#### Remote - OnRamps
#### January 2025 - February 2026

Beginning in my freshman spring, I was employed at OnRamps for their statistics grading team. My responsibilities included coordinating exam assignment with other graders on Smartsheet, attending calibration meetings to ensure each exam was graded consistently and fairly, and providing feedback to high school students on what they succeeded on and where they might need improvement.

## **Program Assistant with UT Computer Science**
#### Austin, TX - The University of Texas at Austin
#### July 2024 - July 2025

My interest in UT was sparked by attending the Computer Science: Academy for Women program they host annually. The program combines rigorous education on computer science with spending time enjoying campus. As a PA, I was present for a set of about 12-15 high school girls from breakfast until dinner. 

I was tasked with providing campus tours of UT Austin, facilitating conversation and friendship within my group, and accompanying students on company tours. My duties varied depending on the day, but what remained consistent were the five hours of lab the students attended every day. These labs included a crash course on Linux and C++, which the students then used to construct an interactive lightshow using LED lights and a Rasberry Pi.

------------------------------------------------------------------------

# Volunteering

## **High School Swim Coaching**
#### Sugar Land, TX - Logos Preparatory Academy
#### September 2022 - January 2025
After a shoulder injury left me unable to compete, I sought new ways to give back to my team and serve my coach, even if it wasn't through being in the water myself. Unsure of what to do, I continued showing up to practice, doing various tasks for the team: passing out equipment, recording times, and cleaning up on deck. This opened the door for filling in for the coach when she was occupied with another lane, then later managing my own set of lanes, and eventually writing sets, critiquing technique, and mentoring each swimmer I was assigned.

I volunteered as the team's manager every fall semester until the end of swim season in February. During this time, I attended meets to cheer on and talk to athletes before and after races, compared times, adjusted sets as needed, and provided advice wherever I could. The best parts of this opportunity were the connections I fostered with both middle and high school swimmers at my school, as I got to watch each grow not just in speed and skill, but also in confidence, maturity, and passion for this sport.

------------------------------------------------------------------------
